services:
  - type: web
    name: finance-api
    plan: free
    runtime: node
    rootDir: finance-backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - finance-backend/**
        - render.yaml
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: DB_SYNC
        value: false
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://finance-frontend-pxh9.onrender.com

  - type: web
    name: finance-frontend
    plan: free
    runtime: node
    rootDir: finance-frontend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    buildFilter:
      paths:
        - finance-frontend/**
        - render.yaml
    envVars:
      - key: REACT_APP_API_URL
        value: https://finance-api-x1ig.onrender.com/api
      - key: REACT_APP_GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
